[2024-06-22T12:21:44.972+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_ml_pipeline_class_reg.run_modeling_classification manual__2024-06-22T12:21:37.426488+00:00 [queued]>
[2024-06-22T12:21:44.983+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_ml_pipeline_class_reg.run_modeling_classification manual__2024-06-22T12:21:37.426488+00:00 [queued]>
[2024-06-22T12:21:44.985+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-06-22T12:21:45.005+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_modeling_classification> on 2024-06-22 12:21:37.426488+00:00
[2024-06-22T12:21:45.013+0000] {standard_task_runner.py:60} INFO - Started process 2671 to run task
[2024-06-22T12:21:45.016+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_ml_pipeline_class_reg', 'run_modeling_classification', 'manual__2024-06-22T12:21:37.426488+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/run_data_wrangling_class_reg.py', '--cfg-path', '/tmp/tmpl416z9vn']
[2024-06-22T12:21:45.020+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask run_modeling_classification
[2024-06-22T12:21:45.088+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_ml_pipeline_class_reg.run_modeling_classification manual__2024-06-22T12:21:37.426488+00:00 [running]> on host 0fdcf3d7bc80
[2024-06-22T12:21:45.196+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_ml_pipeline_class_reg' AIRFLOW_CTX_TASK_ID='run_modeling_classification' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T12:21:37.426488+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T12:21:37.426488+00:00'
[2024-06-22T12:21:45.198+0000] {logging_mixin.py:188} INFO - Looking for .env file at: /opt/***/config/.env
[2024-06-22T12:21:45.223+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2024-06-22T12:21:46.664+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.4.2 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

[2024-06-22T12:21:47.026+0000] {logging_mixin.py:188} INFO - Demurrage Prediction file saved to s3://logimo-outbound/ship_cost_predictor/ship_cost_classification/Data_Pred_Demurrage_True_Join.csv for regressor ingestion
[2024-06-22T12:21:47.029+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-06-22T12:21:47.313+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=DAG_ml_pipeline_class_reg, task_id=run_modeling_classification, execution_date=20240622T122137, start_date=20240622T122144, end_date=20240622T122147
[2024-06-22T12:21:47.365+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-22T12:21:47.397+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
